enum ServerErrorStatus {
  error = 'error',
  failure = 'failure',
}

/**
 * expended error object for express route purposes
 * @param message the error message
 * @param statusCode the error status code
 */
export default class ServerError extends Error {
  // indicated if it's validation error or not
  status: ServerErrorStatus;

  // indicates if this error was generated by us or not
  isPlaned: boolean;

  constructor(message: string, private statusCode: number) {
    super(message);
    this.status = /^4/.test(`${this.statusCode}`) ? ServerErrorStatus.failure : ServerErrorStatus.error;
    this.isPlaned = true;

    // representing the location in the code at which the error was thrown/returned.
    Error.captureStackTrace(this, this.constructor);
  }
}
